# Happenings
-- Inspiration found from meetup.com
INSERT INTO happenings VALUES (1,"Solving Real World Problems via ML",
								"2021-04-08	06:00:00",
								"2021-04-08 07:30:00",
                                "We will have 3 experts from across the community to speak about their particular application of machine learning methods and the challenges they currently face...",
                                "Education",
                                "Online",
                                13),(2,"Mountain biking/cycling/walking brewery",
								"2021-04-18 12:00:00",
								"2021-04-18 15:00:00",
                                "There will generally be no organiser on this event - but you only need to meet up and go for a walk/ride and have a chat. You can do that on your own - can't you...",
                                "Active",
                                "Stationsvej 5, 3500 Værløse, Copenhagen, dk",
                                7),(3,"Switzerland Alpine Hut Tour",
								"2021-07-18 15:00:00",
								"2021-07-22 17:00:00",
                                "ITS TIME TO MAKE SOME PLANS TO TRAVEL POST COIVD AND BOOK SOMETHING BEFORE IT GETS EXPENSIVE!...",
                                "Active",
                                "Bex",
                                8),(4,"VS Code v1.55 Release Party 🎉",
								"2021-04-08 08:00:00",
								"2021-04-08 08:30:00",
                                "Woohoo! The latest VS Code release is almost out and we want to celebrate with y'all! Join our...",
                                "Conversation",
                                "Online",
                                2),(5,"Hvordan man (ikke) kan forudse et radiohit",
								"2021-04-12 16:00:00",
								"2021-04-12 17:00:00",
                                "Kan man forudse hvilken sang der bliver det næste store radiohit? Oliver Fuglsang Grooss, Ph.d...",
                                "Presentation",
                                "Online",
                                4);
